# Generated by Django 4.2.10 on 2024-04-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0109_alter_variable_value_class'),
        ('mqtt', '0001_add_device_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedMQTTBroker',
            fields=[
            ],
            options={
                'verbose_name': 'MQTT Broker',
                'verbose_name_plural': 'MQTT Brokers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pyscada.device',),
        ),
        migrations.CreateModel(
            name='ExtendedMQTTVariable',
            fields=[
            ],
            options={
                'verbose_name': 'MQTT Variable',
                'verbose_name_plural': 'MQTT Variables',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pyscada.variable',),
        ),
        migrations.CreateModel(
            name='MQTTVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('topic_parser', models.CharField(blank=True, help_text='a regular expression for parsing the value, leave blank to just parse by float, int or bool', max_length=255, null=True)),
                ('timestamp_topic', models.CharField(blank=True, help_text='the topic where the timstamp is published, leave blank to use the receive timestamp', max_length=255, null=True)),
                ('timestamp_parser', models.CharField(default='%i', help_text='a string of format codes strptime, or %i for isoformat', max_length=255)),
                ('mqtt_variable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.variable')),
            ],
        ),
        migrations.CreateModel(
            name='MQTTBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('port', models.PositiveIntegerField(default=1883, help_text='default ports for MQTT are 1883 and 8883')),
                ('timeout', models.PositiveIntegerField(default=60)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('mqtt_broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.device')),
            ],
        ),
    ]
